task2
froggypol/phoneshop pull request #2
Opened 2020-02-16 11:12 UTC by froggypol

sorting, searching methods

2020-03-08 07:42 UTC, Alastifer requested changes

2020-03-08 07:42 UTC, Alastifer commented on core/src/main/java/com/es/core/cart/AjaxResponseBody.java
> +public class AjaxResponseBody {
называй классы нормально

2020-03-08 07:42 UTC, Alastifer commented on core/src/main/java/com/es/core/cart/Cart.java
> +    private List<CartItem> cartItemList;
cartItems

2020-03-08 07:42 UTC, Alastifer commented on core/src/main/java/com/es/core/cart/CartInfo.java
> +public class CartInfo {
CartData or CartForm (если передаешь с сайта инфу)

2020-03-08 07:42 UTC, Alastifer commented on core/src/main/java/com/es/core/cart/CartItem.java
> +    private Phone phone;
зачем тебе телефон как бин?

2020-03-08 07:42 UTC, Alastifer commented on core/src/main/java/com/es/core/cart/CartService.java
> +    Cart getCart(HttpSession request);
во-первых что за дичь в параметре? а во-вторых в getCart мы ничего передавать не будем

2020-03-08 07:42 UTC, Alastifer commented on core/src/main/java/com/es/core/cart/CartService.java
> +    void addPhone(Long phoneId, Long quantity, HttpSession httpSession);
сессию не передаём

2020-03-08 07:42 UTC, Alastifer commented on core/src/main/java/com/es/core/cart/HttpSessionCartService.java
> +    JdbcTemplate jdbcTemplate;
private

2020-03-08 07:42 UTC, Alastifer commented on core/src/main/java/com/es/core/DTO/CartInfoDTO.java
> +public class CartInfoDTO {
CartData

2020-03-08 07:42 UTC, Alastifer commented on core/src/main/java/com/es/core/DTO/CartInfoDTO.java
> +    private Long quantityToAdd;
зачем тут валидация? валидация только в формах нужна, а это у тебя data

2020-03-08 07:42 UTC, Alastifer commented on core/src/main/java/com/es/core/ajax/response/AjaxResponseBody.java
> +public class AjaxResponseBody {
название ни о чем

2020-03-08 07:42 UTC, Alastifer commented on core/src/main/java/com/es/core/converter/AjaxAddingToCartConverter.java
> +public class AjaxAddingToCartConverter implements Converter<AjaxAddingToCartForm, AjaxAddingToCartModel> {
не надо ajax добавлять в классы, которые юзаются для ajax запросов. У нас есть только model, data и form

2020-03-08 07:42 UTC, Alastifer commented on core/src/main/java/com/es/core/converter/AjaxAddingToCartConverter.java
> +    private List<AjaxAddingToCartDataPopulator> ajaxAddingToCartDataPopulators;
просто populators

2020-03-08 07:42 UTC, Alastifer commented on core/src/main/java/com/es/core/converter/CartDataConverter.java
> +        cartPopulators.stream().forEach(populator -> populator.populate(cart, cartData));
вроде у листа есть свой forEach

2020-03-08 07:42 UTC, Alastifer commented on core/src/main/java/com/es/core/dao/JdbcPhoneDao.java
> +        return  getPhoneListWithColors().stream()
лишний пробел

2020-03-08 07:42 UTC, Alastifer commented on core/src/main/java/com/es/core/facade/AjaxAddingToCartFacade.java
> +import com.es.core.DTO.CartInfoDTO;
dto с маленьких для пакета

2020-03-08 07:42 UTC, Alastifer commented on core/src/main/java/com/es/core/listener/Listener.java
> +package com.es.core.listener;
фикси

2020-03-08 07:42 UTC, Alastifer commented on core/src/main/java/com/es/core/service/PagingService.java
> +package com.es.core.service;
фикси

2020-03-08 07:42 UTC, Alastifer commented on core/src/main/java/com/es/core/sorting/FindAndSortInDataBase.java
> +public class FindAndSortInDataBase {
это вообще что?

2020-03-08 07:42 UTC, Alastifer commented on core/src/main/java/com/es/core/sorting/FindAndSortInDataBase.java
> +    @Autowired
почему не resource?

2020-03-08 07:42 UTC, Alastifer commented on core/src/main/java/com/es/core/sorting/FindAndSortInDataBase.java
> +package com.es.core.sorting;
фикси

2020-03-08 07:42 UTC, Alastifer commented on web/src/main/java/com/es/phoneshop/web/controller/AjaxCartController.java
>  public class AjaxCartController {
название норм придумай

2020-03-08 07:42 UTC, Alastifer commented on web/src/main/java/com/es/phoneshop/web/controller/AjaxCartController.java
> +            return  ajaxAddingToCartFacade.updatingInvalidInput();
?:

2020-03-08 07:42 UTC, Alastifer commented on web/src/main/java/com/es/phoneshop/web/controller/pages/ProductListPageController.java
> +    private JdbcPhoneDaoFacade jdbcPhoneDaoFacade;
что за странное название?

2020-03-08 07:42 UTC, Alastifer commented on web/src/main/webapp/WEB-INF/dispatcher-servlet.xml
> +    <mvc:annotation-driven/>
зачем?

2020-03-08 07:42 UTC, Alastifer commented on core/src/main/java/com/es/core/facade/JdbcPhoneDaoFacade.java
> +package com.es.core.facade;
фикси

2020-03-08 09:32 UTC, froggypol commented on core/src/main/java/com/es/core/sorting/FindAndSortInDataBase.java
> +public class FindAndSortInDataBase {
это для сортировки и/или поиска по именр

2020-03-15 16:32 UTC, Alastifer requested changes

2020-03-15 16:32 UTC, Alastifer commented on core/src/main/java/com/es/service/PagingService.java
> +public class PagingService {
это смашивает на дао

2020-03-15 16:32 UTC, Alastifer commented on web/src/main/java/com/es/phoneshop/web/controller/AddToCartController.java
> +    @RequestMapping(value = "/ajaxCart", method = RequestMethod.POST)
ajaxCart такое себе

2020-03-15 16:32 UTC, Alastifer commented on web/src/main/java/com/es/phoneshop/web/controller/AddToCartController.java
> +    public ResponseEntity updateCartViaAjax(@Valid @RequestBody AddingToCartForm cartForm, BindingResult bindingResult) throws OutOfStockException {
requestBody и valid поменяй местами

2020-03-15 16:32 UTC, Alastifer commented on web/src/main/java/com/es/phoneshop/web/controller/pages/ProductListPageController.java
> +    private ProductListFacade jdbcPhoneDaoFacade;
jdbcPhoneDaoFacade мешанка всего и сразу

2020-03-15 17:57 UTC, Alastifer approved these changes

2020-03-15 17:57 UTC, merged